"""empty message

Revision ID: d0965cfe1e27
Revises: dcb06f323848
Create Date: 2020-01-10 12:19:05.132654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0965cfe1e27'
down_revision = 'dcb06f323848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_user_id_fkey', 'post', type_='foreignkey')
    op.drop_column('post', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('post_user_id_fkey', 'post', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
